  app:
    build: .
    container_name: entitlements-app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: employee_entitlements
      DB_USER: root
      DB_PASS: password
    ports:
      - "8888:80"
    restart: always
