version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: entitlements-db
    restart: always
    environment:
      MYSQL_DATABASE: employee_entitlements
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  app:
    build: .
    container_name: entitlements-app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: employee_entitlements
      DB_USER: root
      DB_PASS: password
    ports:
      - "8888:80"
    volumes:
      - .:/var/www/html
    restart: always
    command: ["bash", "-c", "chmod -R 755 /var/www/html && apache2-foreground"]

volumes:
  db_data:
